name: Build IPA for eSign

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build iOS
      run: |
        flutter build ios --release --no-codesign
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Create IPA
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath Runner.xcarchive \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   archive
                   
        xcodebuild -exportArchive \
                   -archivePath Runner.xcarchive \
                   -exportPath . \
                   -exportOptionsPlist ExportOptions.plist \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO
                   
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ppapikey-ipa
        path: ios/*.ipa
