name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate Flutter files
      run: |
        flutter packages get
        flutter precache --ios
        
    - name: Setup CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        
    - name: Build iOS app (Debug)
      run: |
        flutter build ios --debug --simulator
        
    - name: Build iOS app (Release)
      run: |
        flutter build ios --release --simulator