name: Build IPA (Requires Apple Developer Account)

on:
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate Flutter files
      run: |
        flutter packages get
        flutter precache --ios
        
    - name: Setup CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --repo-update
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build IPA
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath Runner.xcarchive \
                   archive
                   
        xcodebuild -exportArchive \
                   -archivePath Runner.xcarchive \
                   -exportPath . \
                   -exportOptionsPlist ExportOptions.plist
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v3
      with:
        name: ppapikey-app-ipa
        path: ios/*.ipa
        retention-days: 30
