name: Simple iOS Build Test

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Check Flutter installation
      run: |
        flutter --version
        flutter doctor -v
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Check project structure
      run: |
        ls -la
        ls -la ios/
        ls -la ios/Flutter/
        
    - name: Test Flutter build
      run: |
        flutter build ios --debug --no-codesign
